name: Build and Publish Image

on:
  push:
    tags:
      - "v*"  # 匹配所有以 v 开头的标签（如 v1.0.0）
    branches: [ master ]  # 触发分支

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # 格式：<用户名/仓库名>

jobs:
  build-podman-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 需要此权限推送镜像到GHCR

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 安装 Podman
    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    # 登录容器仓库
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 构建镜像并设置标签
    - name: Build with Podman
      run: |
        # 获取架构信息
        ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/' -e 's/armv7l/arm/')        
       
        # 构建镜像标签
        TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref }}
        SHA_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

        # 执行构建
        podman build \
          --build-arg ARCH="$ARCH" \
          -t "$TAG" \
          -t "$SHA_TAG" \
          -f Dockerfile.distroless \
          .

        # 推送镜像
        podman push "$TAG"
        podman push "$SHA_TAG"
